version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "python"
      - "backend"
    assignees:
      - "backend-team"
    commit-message:
      prefix: "deps(backend)"
      prefix-development: "deps(backend-dev)"
      include: "scope"
    versioning-strategy: "lockfile-only"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "dependency-reviewers"

  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    assignees:
      - "frontend-team"
    commit-message:
      prefix: "deps(web)"
      prefix-development: "deps(web-dev)"
      include: "scope"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "dependency-reviewers"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    labels:
      - "dependencies"
      - "docker"
      - "backend"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "deps(docker-backend)"
      include: "scope"
    open-pull-requests-limit: 3

  - package-ecosystem: "docker"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "deps(docker-web)"
      include: "scope"
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform"
    directory: "/infrastructure/terraform"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "deps(terraform)"
      include: "scope"
    open-pull-requests-limit: 5