{
  "name": "brik-refunds-service",
  "version": "1.0.0",
  "description": "Comprehensive refund processing module for the Brik platform",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "eslint . --ext .ts,.tsx",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:coverage": "jest --coverage",
    "typecheck": "tsc --noEmit",
    "format": "prettier --write \"**/*.{ts,tsx,js,json,css}\"",
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "engines": {
    "node": ">=18.0.0",
    "npm": ">=9.0.0"
  },
  "dependencies": {
    "@auth0/auth0-react": "^2.2.0",
    "@reduxjs/toolkit": "^1.9.5",
    "@tanstack/react-query": "^4.32.5",
    "@tanstack/react-table": "^8.9.3",
    "axios": "^1.4.0",
    "chart.js": "^4.3.2",
    "classnames": "^2.3.2",
    "date-fns": "^2.30.0",
    "decimal.js": "^10.4.3",
    "formik": "^2.4.2",
    "i18next": "^23.2.11",
    "jotai": "^2.2.2",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "next": "^13.4.12",
    "react": "^18.2.0",
    "react-chartjs-2": "^5.2.0",
    "react-dom": "^18.2.0",
    "react-dropzone": "^14.2.3",
    "react-i18next": "^13.0.1",
    "react-icons": "^4.10.1",
    "react-redux": "^8.1.1",
    "react-toastify": "^9.1.3",
    "recharts": "^2.7.2",
    "swr": "^2.2.0",
    "tailwindcss": "^3.3.3",
    "yup": "^1.2.0",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^7.1.0",
    "@storybook/addon-interactions": "^7.1.0",
    "@storybook/addon-links": "^7.1.0",
    "@storybook/blocks": "^7.1.0",
    "@storybook/nextjs": "^7.1.0",
    "@storybook/react": "^7.1.0",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/jest": "^29.5.3",
    "@types/lodash": "^4.14.195",
    "@types/node": "^20.4.4",
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.1.0",
    "@typescript-eslint/parser": "^6.1.0",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.45.0",
    "eslint-config-next": "^13.4.12",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jest": "^27.2.3",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.33.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-storybook": "^0.6.12",
    "husky": "^8.0.3",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^29.6.1",
    "jest-environment-jsdom": "^29.6.1",
    "lint-staged": "^13.2.3",
    "msw": "^1.2.2",
    "postcss": "^8.4.27",
    "prettier": "^3.0.0",
    "storybook": "^7.1.0",
    "ts-jest": "^29.1.1",
    "typescript": "^5.1.6"
  },
  "lint-staged": {
    "*.{ts,tsx}": ["eslint --fix", "prettier --write"],
    "*.{json,css,md}": ["prettier --write"]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "pre-push": "npm run typecheck && npm run test"
    }
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}